version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
    ignore:
      - dependency-name: "NUnit"
        update-types: ["version-update:semver-major"]
    groups:
      nuget-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: weekly
      day: wednesday