version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
    groups:
      nuget-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: NUnit
        update-types:
          - "version-update:semver-major"
      - dependency-name: "AutoFixture*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: weekly
      day: wednesday
